# -*- coding: utf-8 -*-
"""decision_tree.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CZDd0nOrgUuKkV8cCbXngTQy3tuyOsUS
"""

from google.colab import drive
drive.mount('/content/drive')
path = '/content/drive/MyDrive/sem8/siv810/'
import sys
sys.path.append('/content/drive/MyDrive/sem8/siv810/models')
from backend import *

"""Hyperparameters"""

params = []
# different hyperparameters to be tried
criterion = ['gini', 'entropy']
splitter = ['best', 'random']

# merge all hyperparams
params.append(criterion)
params.append(splitter)
params = permute_hyperparams(params)

classifier_class = decision_tree

"""Dataset 1"""

dataset_id = 1

run_all_for_one_dataset(classifier_class, params, path, dataset_id, run_type = "normal", all = False, normalize = True)

run_all_for_one_dataset(classifier_class, params, path, dataset_id, run_type = "normal", all = False, normalize = False)

run_all_for_one_dataset(classifier_class, params, path, dataset_id, run_type = "pca", all = True, normalize = False)

"""Dataset 2"""

dataset_id = 2

run_all_for_one_dataset(classifier_class, params, path, dataset_id, run_type = "normal", all = False, normalize = True)

run_all_for_one_dataset(classifier_class, params, path, dataset_id, run_type = "normal", all = False, normalize = False)

run_all_for_one_dataset(classifier_class, params, path, dataset_id, run_type = "pca", all = True, normalize = False)

"""Dataset 3"""

dataset_id = 3

run_all_for_one_dataset(classifier_class, params, path, dataset_id, run_type = "normal", all = False, normalize = True)

run_all_for_one_dataset(classifier_class, params, path, dataset_id, run_type = "normal", all = False, normalize = False)

run_all_for_one_dataset(classifier_class, params, path, dataset_id, run_type = "pca", all = True, normalize = False)

"""Dataset 4"""

dataset_id = 4

run_all_for_one_dataset(classifier_class, params, path, dataset_id, run_type = "normal", all = False, normalize = True)

run_all_for_one_dataset(classifier_class, params, path, dataset_id, run_type = "normal", all = False, normalize = False)

run_all_for_one_dataset(classifier_class, params, path, dataset_id, run_type = "pca", all = True, normalize = False)



