# -*- coding: utf-8 -*-
"""xg_boost.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NA9s94q5b4bAAPZ9yu_bqWnTPNrrff_r
"""

# library for XGBoost Classifier
!pip3 install xgboost

from google.colab import drive
drive.mount('/content/drive')
path = '/content/drive/MyDrive/sem8/siv810/'
import sys
sys.path.append('/content/drive/MyDrive/sem8/siv810/models')
from backend import *

"""Hyperparameters"""

params = []
# different hyperparameters to be tried
max_depth = [6, 8]

# merge all hyperparams
params.append(max_depth)
params = permute_hyperparams(params)

classifier_class = xg_boost

"""Dataset 1"""

dataset_id = 1

run_all_for_one_dataset(classifier_class, params, path, dataset_id, run_type = "normal", all = False, normalize = True)

run_all_for_one_dataset(classifier_class, params, path, dataset_id, run_type = "normal", all = False, normalize = False)

run_all_for_one_dataset(classifier_class, params, path, dataset_id, run_type = "pca", all = False, normalize = False)

"""Dataset 2"""

dataset_id = 2

run_all_for_one_dataset(classifier_class, params, path, dataset_id, run_type = "normal", all = False, normalize = True)

run_all_for_one_dataset(classifier_class, params, path, dataset_id, run_type = "normal", all = False, normalize = False)

run_all_for_one_dataset(classifier_class, params, path, dataset_id, run_type = "pca", all = False, normalize = False)

"""Dataset 3"""

dataset_id = 3

run_all_for_one_dataset(classifier_class, params, path, dataset_id, run_type = "normal", all = False, normalize = True)

run_all_for_one_dataset(classifier_class, params, path, dataset_id, run_type = "normal", all = False, normalize = False)

run_all_for_one_dataset(classifier_class, params, path, dataset_id, run_type = "pca", all = False, normalize = False)

"""Dataset 4"""

dataset_id = 4

run_all_for_one_dataset(classifier_class, params, path, dataset_id, run_type = "normal", all = False, normalize = True)

run_all_for_one_dataset(classifier_class, params, path, dataset_id, run_type = "normal", all = False, normalize = False)

run_all_for_one_dataset(classifier_class, params, path, dataset_id, run_type = "pca", all = False, normalize = False)



